In [20]:
import pandas as pd
import numpy as np
from keras.preprocessing.sequence import pad_sequences

In [30]:
data_df = pd.read_csv("Data/data_with_industry_codes.csv")
questions_df = pd.read_csv("Data/questions.csv")
questions_df = questions_df.filter(['questions_id','questions_title','questions_date_added','questions_body'])
best_answer_df = pd.merge(data_df, questions_df, on="questions_id")
best_answer_df = best_answer_df.drop(columns=['Unnamed: 0'])
best_answer_df_short = best_answer_df.head(10)
best_answer_df_short

,questions_id,answers_id,professionals_industry,industry_codes,questions_title,questions_date_added,questions_body
0,0914db8647f14ed18ab2a7b321d0b81d,72798b8492314e12980a1503633d6569,Other,274,Is most of your day spent working when being a...,2012-10-13 05:11:32 UTC+0000,I want to know how much of my day will be used...
1,2c5bd5eb628245acb868c81fefcfe5e0,281c2557f0154dde984707e40100b8b4,Other,274,About how much money does a pediatrician make ...,2012-02-07 13:24:09 UTC+0000,<p>I would like to be a pediatrician and would...
2,2f2378acab3f444199ee2b69d2d3626f,63b7a06323ee4d578a37cf780debfa58,Other,274,Do employers hire you based on what college yo...,2012-09-09 04:02:51 UTC+0000,"Hi, I am a sophomore and I just wanted to know..."
3,333464d7484b43e3866e86096bc4ddb9,683b200ad5014e84a441db677f990d75,Other,274,What are the best ways to prepare for intervie...,2011-09-27 15:24:27 UTC+0000,"McKinsey, Bain, BCG, mainly.\r\n\r\nLooking fo..."
4,5bd585028efe49f4b89701b84e6fbe8c,d0388adf192c4683a1d9a079f88fbd52,Other,274,"If you want to be a police detective, what wou...",2012-06-01 15:18:30 UTC+0000,"<p>Hello , My name is Danielle and I go to a s..."
5,82acf6d8608b4743848d0c8c4e5c610b,ae8d6e375f804c698c324def1a3bf4f9,Other,274,What is it like to deliver a baby?,2012-09-07 19:06:11 UTC+0000,I am a sophomore who is interested in learning...
6,b3534776e3854e8bb73d8a1b1be3511f,f46ad30f5220449f9ac36f66f49ba310,Other,274,What courses will I be doing to become a veter...,2012-09-07 19:00:50 UTC+0000,I want to know what type of courses I will be ...
7,d98717b213984ed1a715bd88367d6258,a836064f4eaf491eaeb4142e8d4cd752,Other,274,Is being a level 3 Neonatal Nurse emotionally ...,2012-09-09 01:03:23 UTC+0000,I am a sophomore thinking about becoming a Neo...
8,7f00ff6f131243c880ced983e171a085,9a2997e6ddd94c8b9a2bc00044c434d0,Other,274,What colleges are recommended the most to know...,2012-09-07 19:01:48 UTC+0000,I am a 10th grader. I am still trying to figur...
9,e999912603ee4a5c908c4aa68f8f46ba,ea0d1620028e49edbce31e248e0a78e3,Other,274,Does being a Artist include being able to make...,2012-01-06 19:58:22 UTC+0000,I would like to be able to be an artist that c...

In [31]:
from cypher import encode
from datetime import datetime

In [35]:
best_answer_df['indexed'] = best_answer_df.apply(lambda x: encode(x['questions_title'], x['questions_body']), axis=1)

In [36]:
best_answer_df.head()

,questions_id,answers_id,professionals_industry,industry_codes,questions_title,questions_date_added,questions_body,indexed
0,0914db8647f14ed18ab2a7b321d0b81d,72798b8492314e12980a1503633d6569,Other,274,Is most of your day spent working when being a...,2012-10-13 05:11:32 UTC+0000,I want to know how much of my day will be used...,"[1, 17454, 2, 18423, 18305, 18447, 18301, 1842..."
1,2c5bd5eb628245acb868c81fefcfe5e0,281c2557f0154dde984707e40100b8b4,Other,274,About how much money does a pediatrician make ...,2012-02-07 13:24:09 UTC+0000,<p>I would like to be a pediatrician and would...,"[1, 18412, 2, 15586, 17447, 18080, 14578, 1744..."
2,2f2378acab3f444199ee2b69d2d3626f,63b7a06323ee4d578a37cf780debfa58,Other,274,Do employers hire you based on what college yo...,2012-09-09 04:02:51 UTC+0000,"Hi, I am a sophomore and I just wanted to know...","[1, 2, 55, 17641, 18088, 18305, 17831, 16001, ..."
3,333464d7484b43e3866e86096bc4ddb9,683b200ad5014e84a441db677f990d75,Other,274,What are the best ways to prepare for intervie...,2011-09-27 15:24:27 UTC+0000,"McKinsey, Bain, BCG, mainly.\r\n\r\nLooking fo...","[1, 17880, 2, 11793, 11794, 12066, 12218, 1808..."
4,5bd585028efe49f4b89701b84e6fbe8c,d0388adf192c4683a1d9a079f88fbd52,Other,274,"If you want to be a police detective, what wou...",2012-06-01 15:18:30 UTC+0000,"<p>Hello , My name is Danielle and I go to a s...","[1, 2, 15586, 230, 252, 5487, 18461, 14040, 10..."

In [37]:
indexed_padded = pad_sequences(best_answer_df['indexed'], value=0, padding='post', maxlen=50)

In [38]:
indexed_padded[666]

array([    1, 16015,     2, 18456, 17155, 18471, 18170, 17949, 18064,
       17514, 17578, 17514,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0])

In [39]:
import keras
import tensorflow as tf

In [40]:
# input shape is the vocabulary count used for the movie reviews (10,000 words)
vocab_size = 10000
model = keras.Sequential()
model.add(keras.layers.Embedding(vocab_size, 16))
model.add(keras.layers.GlobalAveragePooling1D())
model.add(keras.layers.Dense(16, activation=tf.nn.relu))
model.add(keras.layers.Dense(380, activation=tf.nn.relu))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
embedding_2 (Embedding)      (None, None, 16)          160000
_________________________________________________________________
global_average_pooling1d_2 ( (None, 16)                0
_________________________________________________________________
dense_3 (Dense)              (None, 16)                272
_________________________________________________________________
dense_4 (Dense)              (None, 380)               6460
=================================================================
Total params: 166,732
Trainable params: 166,732
Non-trainable params: 0
_________________________________________________________________

In [3]:
from sklearn.model_selection import train_test_split

X=indexed_padded

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

NameError: name 'indexed_padded' is not defined