In [30]:
import pandas as pd
import numpy as np
from keras.preprocessing.sequence import pad_sequences

Using TensorFlow backend.

In [19]:
data_df = pd.read_csv("Data/data.csv")
questions_df = pd.read_csv("Data/questions.csv")
questions_df = questions_df.filter(['questions_id','questions_title','questions_date_added'])
best_answer_df = pd.merge(data_df, questions_df, on="questions_id")
best_answer_df_short = best_answer_df.head(10)
best_answer_df_short

,professionals_industry,questions_body,questions_id,questions_title,questions_date_added
0,Mental Health Care,What is a maths teacher? what is a ma...,332a511f1569444485cf7a7a556a5e54,Teacher career question,2016-04-26 11:14:26 UTC+0000
1,Mental Health Care,I like soccer because i been playing sense i w...,0f1d6a4f276c4a05878dd48e03e52289,what kind of college could i go to for a soc...,2016-05-19 22:16:25 UTC+0000
2,Mental Health Care,"I am interested in Computational Neuroscience,...",0149c6d63e214040b44d4a3789bb00ba,What is the best way to prepare for studying e...,2018-04-12 17:13:45 UTC+0000
3,Computer Software,"I am interested in Computational Neuroscience,...",0149c6d63e214040b44d4a3789bb00ba,What is the best way to prepare for studying e...,2018-04-12 17:13:45 UTC+0000
4,Mental Health Care,"I am a Sociology, Political Science, and Inter...",acc611cfb5c44daa8a3d7d65dfffa5ff,How should I prepare myself for my job search ...,2018-08-14 04:49:33 UTC+0000
5,Mental Health Care,I am currently enrolled in a World Musics clas...,b44409c0c83a43578f4f2d0a0e4d8ead,What majors do you recommend in order to be an...,2016-12-07 20:43:41 UTC+0000
6,Music,I am currently enrolled in a World Musics clas...,b44409c0c83a43578f4f2d0a0e4d8ead,What majors do you recommend in order to be an...,2016-12-07 20:43:41 UTC+0000
7,Mental Health Care,My question regards the potential to find empl...,27653986401c4a8388d03cfa28acf5b4,How much opportunity is there for a STEM major...,2016-10-20 19:28:36 UTC+0000
8,Entertainment,My question regards the potential to find empl...,27653986401c4a8388d03cfa28acf5b4,How much opportunity is there for a STEM major...,2016-10-20 19:28:36 UTC+0000
9,Mental Health Care,college job,7017565a7f0141dbb47a3445ed128e34,If I cannot find a job in my career field afte...,2018-10-05 13:28:50 UTC+0000

In [20]:
from cypher import encode
from datetime import datetime

In [21]:
for i in np.arange(0,len(best_answer_df_short)):
    best_answer_df_short.iloc[i]['indexed'] = encode(str(best_answer_df_short["questions_title"]), str(best_answer_df_short["questions_body"]))

In [27]:
best_answer_df['indexed'] = best_answer_df.apply(lambda x: encode(x['questions_title'], x['questions_body']), axis=1)

In [28]:
best_answer_df.head()

,professionals_industry,questions_body,questions_id,questions_title,questions_date_added,indexed
0,Mental Health Care,What is a maths teacher? what is a ma...,332a511f1569444485cf7a7a556a5e54,Teacher career question,2016-04-26 11:14:26 UTC+0000,"[1, 18176, 2, 15779, 16000, 15779, 16000, 1836..."
1,Mental Health Care,I like soccer because i been playing sense i w...,0f1d6a4f276c4a05878dd48e03e52289,what kind of college could i go to for a soc...,2016-05-19 22:16:25 UTC+0000,"[1, 14532, 2, 18080, 18177, 16417, 17345, 1817..."
2,Mental Health Care,"I am interested in Computational Neuroscience,...",0149c6d63e214040b44d4a3789bb00ba,What is the best way to prepare for studying e...,2018-04-12 17:13:45 UTC+0000,"[1, 14040, 2, 16978, 77, 17266, 17743, 18103, ..."
3,Computer Software,"I am interested in Computational Neuroscience,...",0149c6d63e214040b44d4a3789bb00ba,What is the best way to prepare for studying e...,2018-04-12 17:13:45 UTC+0000,"[1, 14040, 2, 16978, 77, 17266, 17743, 18103, ..."
4,Mental Health Care,"I am a Sociology, Political Science, and Inter...",acc611cfb5c44daa8a3d7d65dfffa5ff,How should I prepare myself for my job search ...,2018-08-14 04:49:33 UTC+0000,"[1, 16545, 2, 92, 13293, 14947, 15289, 16015, ..."

In [26]:
best_answer_df_short.head()

,professionals_industry,questions_body,questions_id,questions_title,questions_date_added,indexed
0,Mental Health Care,What is a maths teacher? what is a ma...,332a511f1569444485cf7a7a556a5e54,Teacher career question,2016-04-26 11:14:26 UTC+0000,"[1, 18176, 2, 15779, 16000, 15779, 16000, 1836..."
1,Mental Health Care,I like soccer because i been playing sense i w...,0f1d6a4f276c4a05878dd48e03e52289,what kind of college could i go to for a soc...,2016-05-19 22:16:25 UTC+0000,"[1, 14532, 2, 18080, 18177, 16417, 17345, 1817..."
2,Mental Health Care,"I am interested in Computational Neuroscience,...",0149c6d63e214040b44d4a3789bb00ba,What is the best way to prepare for studying e...,2018-04-12 17:13:45 UTC+0000,"[1, 14040, 2, 16978, 77, 17266, 17743, 18103, ..."
3,Computer Software,"I am interested in Computational Neuroscience,...",0149c6d63e214040b44d4a3789bb00ba,What is the best way to prepare for studying e...,2018-04-12 17:13:45 UTC+0000,"[1, 14040, 2, 16978, 77, 17266, 17743, 18103, ..."
4,Mental Health Care,"I am a Sociology, Political Science, and Inter...",acc611cfb5c44daa8a3d7d65dfffa5ff,How should I prepare myself for my job search ...,2018-08-14 04:49:33 UTC+0000,"[1, 16545, 2, 92, 13293, 14947, 15289, 16015, ..."

In [41]:
best_answer_df['questions_body'].len().max()

AttributeError: 'Series' object has no attribute 'len'

In [45]:
indexed_padded = pad_sequences(best_answer_df['indexed'], value=0, padding='post', maxlen=50)

In [48]:
indexed_padded[666]

array([    1, 16545,     2, 12104, 14054, 16545, 17067, 17919, 18190,
       16545, 12104, 16545,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0])

In [52]:
import keras
import tensorflow as tf

In [54]:
# input shape is the vocabulary count used for the movie reviews (10,000 words)
vocab_size = 10000
model = keras.Sequential()
model.add(keras.layers.Embedding(vocab_size, 16))
model.add(keras.layers.GlobalAveragePooling1D())
model.add(keras.layers.Dense(16, activation=tf.nn.relu))
model.add(keras.layers.Dense(380, activation=tf.nn.relu))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
embedding_3 (Embedding)      (None, None, 16)          160000
_________________________________________________________________
global_average_pooling1d_3 ( (None, 16)                0
_________________________________________________________________
dense_3 (Dense)              (None, 16)                272
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 17
=================================================================
Total params: 160,289
Trainable params: 160,289
Non-trainable params: 0
_________________________________________________________________

In [58]:
pros_df = pd.read_csv("Data/professionals_index.csv", header=None)
pros_df

                                                     0    1
0                            ARCHITECTURE_AND_PLANNING    1
1                                             Academia    2
2                                     Academic Advisor    3
3                                           Accounting    4
4                                 Accounting & Finance    5
5    Accounting (broker dealers, hedge funds, priva...    6
6              Accounting, Tax, Operations, Technology    7
7                               Accounting, education     8
8                   Accounting/ Information Technology    9
9           Accounting/Auditing/Learning & Development   10
10                                     Administrative    11
11                              Advertising Technology   12
12                                              Airbnb   13
13                                   Airlines/Aviation   14
14                         Animal Behavior and Welfare   15
15                                           Animation   16
16                                   Apparel & Fashion   17
17                                 Apparel and Fashion   18
18                             Architecture & Planning   19
19                           Architecture and Planning   20
20                                       Art Education   21
21                                     Arts and Crafts   22
22                                          Automotive   23
23                                            Aviation   24
24                                Aviation & Aerospace   25
25                              Aviation and Aerospace   26
26                                             Banking   27
27                                   Banking/Financial   28
28                                    Biology Research   29
29                                 Biomedical research   30
..                                                 ...  ...
350                      Technology, Accounting, Audit  351
351                                 Telecommunications  352
352                    Telecommunications / Technology  353
353  Telecommunications, Software Engineering, Prog...  354
354                   Telecommunications/Entertainment  355
355                       Translation and Localization  356
356                   Transportation/Trucking/Railroad  357
357                                   Travel Insurance  358
358                                          UX Design  359
359                             User Experience Design  360
360                                          Utilities  361
361                                    Venture Capital  362
362                                         Veterinary  363
363                                        Video Games  364
364  Video production/ Corporate narrative/ Busines...  365
365                   Web Design/Marketing/Advertising  366
366                                    Web Development  367
367                                          Wholesale  368
368                                Writing and Editing  369
369          Writing and Editing, film and photography  370
370                      Writing and Editing/Education  371
371                     Writing and Editing; Education  372
372                             education, tech, media  373
373                                       entrepreneur  374
374                                               game  375
375                      high tech security protection  376
376                                    iOS Development  377
377                                          marijuana  378
378                       nonprofit / higher education  379
379                                        video games  380

[380 rows x 2 columns]

In [82]:
#pros_df[1].loc[pros_df[0] == 'high tech security protection'].first()
best_answer_df['prof_index'] = best_answer_df.apply(lambda x: pros_df[1].loc[pros_df[0] == x['professionals_industry']].values, axis=1)

In [83]:
best_answer_df.head()

,professionals_industry,questions_body,questions_id,questions_title,questions_date_added,indexed,prof_index
0,Mental Health Care,What is a maths teacher? what is a ma...,332a511f1569444485cf7a7a556a5e54,Teacher career question,2016-04-26 11:14:26 UTC+0000,"[1, 18176, 2, 15779, 16000, 15779, 16000, 1836...",[239]
1,Mental Health Care,I like soccer because i been playing sense i w...,0f1d6a4f276c4a05878dd48e03e52289,what kind of college could i go to for a soc...,2016-05-19 22:16:25 UTC+0000,"[1, 14532, 2, 18080, 18177, 16417, 17345, 1817...",[239]
2,Mental Health Care,"I am interested in Computational Neuroscience,...",0149c6d63e214040b44d4a3789bb00ba,What is the best way to prepare for studying e...,2018-04-12 17:13:45 UTC+0000,"[1, 14040, 2, 16978, 77, 17266, 17743, 18103, ...",[239]
3,Computer Software,"I am interested in Computational Neuroscience,...",0149c6d63e214040b44d4a3789bb00ba,What is the best way to prepare for studying e...,2018-04-12 17:13:45 UTC+0000,"[1, 14040, 2, 16978, 77, 17266, 17743, 18103, ...",[65]
4,Mental Health Care,"I am a Sociology, Political Science, and Inter...",acc611cfb5c44daa8a3d7d65dfffa5ff,How should I prepare myself for my job search ...,2018-08-14 04:49:33 UTC+0000,"[1, 16545, 2, 92, 13293, 14947, 15289, 16015, ...",[239]

In [ ]:
from sklearn.model_selection import train_test_split

x=indexed_padded

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)