In [151]:
import pandas as pd

In [152]:
a_df = pd.read_csv("answers.csv")
c_df = pd.read_csv("comment_score.csv")

In [153]:
df = pd.merge(a_df, c_df, on='answers_id')
df.head()

,answers_id,answers_author_id,answers_question_id,answers_date_added,answers_body,Unnamed: 0,score,comments
0,4e5f01128cae4f6d8fd697cec5dca60c,36ff3b3666df400f956f8335cf53e09e,332a511f1569444485cf7a7a556a5e54,2016-04-29 19:40:14 UTC+0000,<p>Hi!</p>\n<p>You are asking a very interesti...,3006,0,1
1,f18d7fca363d4b21a81e6683c5a86b96,0c673e046d824ec0ad0ebe012a0673e4,e214acfbe6644d65b889a3268828db9d,2012-10-01 04:35:42 UTC+0000,"<html><head></head><body><p>Hi Deja,</p>\n<p>K...",207,1,1
2,3d56d36b5e644d079d0d7ada4bdcddcf,b1776598991649088c0a00a6e0a2c766,e214acfbe6644d65b889a3268828db9d,2012-09-09 12:20:48 UTC+0000,<ul>\n<li>\n<p>4 years of college</p>\n</li>\n...,167,2,1
3,1011167b308b4f85a79038573b83f30b,714f9104e8b148c090e975f050946ff2,baa937b4cd184a22acfd76249d25042c,2018-03-14 21:38:57 UTC+0000,<p>Hi Cynthia -</p><p><br></p><p>First of all ...,7336,0,1
4,fd16ef8e20b348339bc67639af37a7f5,4dc61581ec7b409bbd037e483f53ba0a,f05b579f2cd3432898f3ba54feee86b6,2018-05-07 16:07:49 UTC+0000,"<p>Hi Sophie,</p><p> Really interesting qu...",7592,1,1

In [154]:
new_df = df.filter(['answers_question_id', 'answers_date_added','answers_id','answers_author_id','score','comments'])

new_df.head()

,answers_question_id,answers_date_added,answers_id,answers_author_id,score,comments
0,332a511f1569444485cf7a7a556a5e54,2016-04-29 19:40:14 UTC+0000,4e5f01128cae4f6d8fd697cec5dca60c,36ff3b3666df400f956f8335cf53e09e,0,1
1,e214acfbe6644d65b889a3268828db9d,2012-10-01 04:35:42 UTC+0000,f18d7fca363d4b21a81e6683c5a86b96,0c673e046d824ec0ad0ebe012a0673e4,1,1
2,e214acfbe6644d65b889a3268828db9d,2012-09-09 12:20:48 UTC+0000,3d56d36b5e644d079d0d7ada4bdcddcf,b1776598991649088c0a00a6e0a2c766,2,1
3,baa937b4cd184a22acfd76249d25042c,2018-03-14 21:38:57 UTC+0000,1011167b308b4f85a79038573b83f30b,714f9104e8b148c090e975f050946ff2,0,1
4,f05b579f2cd3432898f3ba54feee86b6,2018-05-07 16:07:49 UTC+0000,fd16ef8e20b348339bc67639af37a7f5,4dc61581ec7b409bbd037e483f53ba0a,1,1

In [155]:
df = new_df.sort_values(by = ['answers_question_id', 'answers_date_added'], ascending = [False, True])

df.head(50)

,answers_question_id,answers_date_added,answers_id,answers_author_id,score,comments
1818,ffe4f998cf7c4bf5a38f5406db1ca746,2018-03-01 00:41:33 UTC+0000,1190ed4125aa4a2493b40ad9e37bca9c,84e133c3aa6b402392920181f7077830,1,1
7074,ffe4bf409a1a48baa004654eb0d2e6f2,2017-02-24 02:18:24 UTC+0000,b98a4e35599e44d495022c71ac3f5516,1806af6b93c74d159c7aad68c6e7a35e,0,1
6215,ffc401dcce5d437c86f5f0576c5f3d69,2017-03-25 15:15:33 UTC+0000,45c0a57deead4bd0b641b047aa0ddcd7,65cd85193d2d43c385ca5a5abce62e63,0,1
1684,ffc201f33712429a8e9feb51f106cdf8,2015-09-18 19:06:42 UTC+0000,2657812dde9648c69438e3ca87d07625,a1006e6a58a0447592e2435caa230f78,1,3
1899,ffbbae76b05e4eacbe7d358d041bbe19,2016-10-26 01:22:51 UTC+0000,f9c0a616e8904dcbab66ca15091e45f7,fafeba89ca764bd891862fb8440a2962,0,1
7766,ff91b4d257d049d5b311dba555160f47,2017-01-13 14:08:21 UTC+0000,3f48f0a6f2c54a4eb48cb6950a997214,36ff3b3666df400f956f8335cf53e09e,1,2
7767,ff91b4d257d049d5b311dba555160f47,2017-01-13 19:15:53 UTC+0000,25f22b1be4d5466b961542d45070b1c0,a72bde6ac9e349d195a6d356444c9578,2,1
6933,ff798f02dd91487bbe1db8f5cd369536,2018-03-02 21:34:06 UTC+0000,afc4fe7668714bc8a0b936029af29595,46be2cf3b8fc49b6b8b3e62ee72a75fe,1,1
3259,ff692fbec8174535b8996aad239f0d8f,2016-05-02 23:45:23 UTC+0000,122a1945e5a4402b8498d8d56a66efc7,9cedda83713f492cbc45a2d1999d41a1,2,1
3260,ff692fbec8174535b8996aad239f0d8f,2016-05-03 18:14:46 UTC+0000,010b1d0f729147fc8c04bfe25cf1416f,a921153ba3114aaaaa60fdd5908d7a80,1,1
975,ff61e9c5edab4730b95b9b5a5ad22521,2014-03-12 20:36:56 UTC+0000,f30c11fc50c1416ab0bb8832b2fcfb75,2adab7916b3747af85b2d82e188c1dc3,4,4
1252,ff5c2567db8f4514b3a5924bb17b8613,2014-04-08 18:38:25 UTC+0000,e14ed3431f1f4a6782dfba1190016eb0,24fac8940aff427c848b2a59265c1204,1,2
3146,ff55f240ea6746be9f8443eb4aff9e7e,2014-04-10 03:39:36 UTC+0000,9fbc7b1de5794975b3a574b8d69abe01,6774ee9e8f9247728dbbe896726e911a,1,1
6445,ff4237248d494dbea25d4404a0f7ce65,2016-02-17 17:47:56 UTC+0000,c6fd06cf931e4f8a8ed1b2c5975cacf7,a1006e6a58a0447592e2435caa230f78,2,1
6446,ff4237248d494dbea25d4404a0f7ce65,2016-02-17 22:30:07 UTC+0000,85f96be4fbbd40debdba2aafeb043eac,36ff3b3666df400f956f8335cf53e09e,0,1
6447,ff4237248d494dbea25d4404a0f7ce65,2016-02-17 23:43:29 UTC+0000,fb3674ba521d44faa9351fa7f9642655,36ff3b3666df400f956f8335cf53e09e,0,2
5864,ff398e9a1f0042d1bd86efcd37238659,2015-03-09 20:40:26 UTC+0000,62e524ee9d0c4f08acad62896915745f,bc46e3699d92477ba8c7aa723e54a151,3,1
5448,ff370f5516984405be75626575377889,2012-09-08 15:32:20 UTC+0000,d7ccd7bece7e4e48bdd1c3c23b4053d0,38bc1866f29744f9a003e2e826e3fcb1,2,2
5449,ff370f5516984405be75626575377889,2012-09-08 18:31:29 UTC+0000,5932eb5dc2064f9485b4776e47d96fba,8442ddfd38bc422fb4677785db0630e6,0,2
1795,ff2fd106d1b34701a6d065dfa4cb35ab,2016-10-23 21:29:22 UTC+0000,15680f43b0ad40089d1c9378d5c181d7,5f95b0ac821e4e8e9b4fa9fc8eb9ff61,2,1
4716,ff2001540cc841818d434284446f2d7b,2018-01-17 05:22:00 UTC+0000,7fdbb5a38ced4ed5b885b13a7d38b88c,49ad078f92f74c5ea4892fdc9337b926,2,3
4717,ff2001540cc841818d434284446f2d7b,2018-02-18 17:21:35 UTC+0000,ff403503a12b424788740ebd8a5918bb,8ce1dca4e94240239e4385ed22ef43ce,1,2
1010,fee844aab7a147c2816bc2f1d3c20dbf,2019-01-28 23:57:24 UTC+0000,30901132449849b2aa18f308306e89a2,d02f6d9faac24997a7003a59e5f34bd3,1,2
6805,fece32ef57304e7eb3d88f2fa74c826d,2015-10-25 21:04:18 UTC+0000,c51887df20b941e48b8bbde8b1c87324,a1006e6a58a0447592e2435caa230f78,1,1
3408,fec9bd052db1463db19d54e087008671,2016-11-11 21:36:15 UTC+0000,059576c0c2f7444bb985dbc56dc2f13e,2345ff01e35a45a4bb9f863c2907be39,2,1
7057,fec5ff8a51914a378111db5db8828fc1,2016-06-22 05:14:03 UTC+0000,69daf88afa2147248c19a805c0fd3fc5,4dc7d9040592416f98c0bef1ad2c31f5,0,1
3880,febab3205ee148c380e0eeb6bfa0c45e,2016-04-29 19:27:27 UTC+0000,c8a9a66253974619beb6d551186f64a9,369f1c8646b649f6997eae7809696bd5,0,1
3638,feb9306289f44ede92c94656d153a766,2018-09-03 05:19:06 UTC+0000,fa4416613920459a8a91b1f2bb5d8b28,0d4cd29c55c64547b0488a9cdcb218ce,0,1
1632,fea935775d7c466ca5cb947cc0421062,2016-05-04 22:36:41 UTC+0000,b6307856e59a40579c5d779419eb8438,656f79a3e38d46f8b6a311209cec6690,1,1
2845,fea6b8dbb0c54fe583d9c75729a0d19c,2018-08-20 15:04:23 UTC+0000,0688b307d52e427b915b385ef0f2a3ad,36ff3b3666df400f956f8335cf53e09e,0,1
3165,fe9c44284fd747fd9b9089ce52a48541,2018-04-03 18:20:35 UTC+0000,276706d8d3c74875a8bf9f555dede62f,05ab77d4c6a141b999044ebbf5415b0d,1,1
727,fe8de6caa05a4c93903d34924e4e7ce6,2018-04-11 14:31:03 UTC+0000,f0ed257ba24743369d220b9b0593852e,674513a492bf4c85a2fd7678831d205d,0,2
4733,fe8920de0e014b94be016c8d2785f913,2014-04-09 04:43:03 UTC+0000,d576ec3316a0400780d0c6b20486b77f,6774ee9e8f9247728dbbe896726e911a,6,2
6930,fe7bd5ab276845dc84328e6fe4347f63,2017-10-16 07:20:11 UTC+0000,05bf1bcf76f1494eaf5051aedb039cd3,cc108f1440844808afe5a249fe084490,1,1
6929,fe7bd5ab276845dc84328e6fe4347f63,2017-11-15 21:46:08 UTC+0000,a1e0d16eeab943ecad3c5b5dc6f88e58,54bf5668362d414aa20d24ad04464748,1,1
3836,fe7a1f1606ac43c382ba6095ab5608b0,2017-06-20 17:25:26 UTC+0000,5c6aff78d45e45f49f0681e0cdc0d4a8,076b94e4d4e5471c97a9d42b0f4fda1c,0,3
1524,fe77da4d6b69473ba55439257b3c9655,2016-10-22 04:10:06 UTC+0000,88ce6fe22ed44e1aa4a6d7d36801698d,41149875d05f47a4905cc1466ed6ab34,0,2
4956,fe61c07279dd47669595b29dc3cf8f20,2017-02-22 21:54:08 UTC+0000,93bd02520a2c4fa7a8b81067d72b2170,9e0cb2a2914c4d05be76c85e7ca356a7,0,1
3296,fe57fb165c364afeaa6f8fcef6e9a2e5,2016-05-21 16:57:19 UTC+0000,21059dfbfc00426d80509619c3925f07,58fa5e95fe9e480a9349bbb1d7faaddb,0,1
6538,fe41cc71e6874532b55adfbc422ccbb4,2015-04-08 19:24:51 UTC+0000,f43803ba80d54f838f208a4e2096286d,1e4cc96c24344c8b806c26c3e6746167,4,5
6537,fe41cc71e6874532b55adfbc422ccbb4,2015-04-09 18:02:24 UTC+0000,d7fb378e7f60452eb752a094d7deafc1,c0f7489f842f4ebfa548af41402d9571,3,1
6558,fe196f1fb0314cc486a998a08c72683e,2016-06-12 00:14:43 UTC+0000,861c1b8bc11248a9b7ea570f245ffacb,58fa5e95fe9e480a9349bbb1d7faaddb,2,2
7467,fe17f87daeb746b2b47b84982bbd6f20,2016-06-24 12:49:06 UTC+0000,9f00c65ca01d45a6b349e834c53d8a48,36ff3b3666df400f956f8335cf53e09e,0,2
7468,fe17f87daeb746b2b47b84982bbd6f20,2016-10-22 02:38:04 UTC+0000,d3704d449daa48999123d1cd86fb59f0,6ea2a8a29d904015959ae16913092ac0,1,1
284,fe068ab2674e45dfb88b158f56121bed,2018-07-30 00:42:41 UTC+0000,d276e232803b4bc1b59195f69d6588c7,826e706f2e564d52856aa71abff6a00e,0,1
1347,fdfab11864c0494a8264ad5cf2ede38c,2018-10-04 00:49:33 UTC+0000,84dc56d1ab374d75b4a98639467a2098,9d156b9a1650453fbeeb196f47c89576,1,1
5304,fdf4fb1c340c40a6b95e903ffa25236a,2016-05-12 17:05:18 UTC+0000,700f21ed213346dc8fc68847b496a3cd,e08c6ad14ba24315afc5985dedc71be5,0,1
465,fdf3f99b17f54b35b0884ba19466acc4,2016-07-02 23:32:49 UTC+0000,7349c17766b4451b99a5961f92b76c79,42deada7c50c4859a34615d70193317e,1,1
3120,fdec0920e1914129903131688496b39d,2017-04-19 11:28:48 UTC+0000,ce98c244a7144b9f93809cf682bd8856,be5d23056fcb4f1287c823beec5291e1,1,1
3121,fdec0920e1914129903131688496b39d,2017-04-19 21:07:41 UTC+0000,912330709344468c81c08aeda61b5d5e,cdc811f964f74479a5a8db13aca4698c,2,1

In [156]:
df['q_score'] = (df.answers_question_id != df.answers_question_id.shift()).astype(int)
df.loc[0,'q_score'] = 0

In [157]:
df.head(100)

,answers_question_id,answers_date_added,answers_id,answers_author_id,score,comments,q_score
1818,ffe4f998cf7c4bf5a38f5406db1ca746,2018-03-01 00:41:33 UTC+0000,1190ed4125aa4a2493b40ad9e37bca9c,84e133c3aa6b402392920181f7077830,1,1,1
7074,ffe4bf409a1a48baa004654eb0d2e6f2,2017-02-24 02:18:24 UTC+0000,b98a4e35599e44d495022c71ac3f5516,1806af6b93c74d159c7aad68c6e7a35e,0,1,1
6215,ffc401dcce5d437c86f5f0576c5f3d69,2017-03-25 15:15:33 UTC+0000,45c0a57deead4bd0b641b047aa0ddcd7,65cd85193d2d43c385ca5a5abce62e63,0,1,1
1684,ffc201f33712429a8e9feb51f106cdf8,2015-09-18 19:06:42 UTC+0000,2657812dde9648c69438e3ca87d07625,a1006e6a58a0447592e2435caa230f78,1,3,1
1899,ffbbae76b05e4eacbe7d358d041bbe19,2016-10-26 01:22:51 UTC+0000,f9c0a616e8904dcbab66ca15091e45f7,fafeba89ca764bd891862fb8440a2962,0,1,1
7766,ff91b4d257d049d5b311dba555160f47,2017-01-13 14:08:21 UTC+0000,3f48f0a6f2c54a4eb48cb6950a997214,36ff3b3666df400f956f8335cf53e09e,1,2,1
7767,ff91b4d257d049d5b311dba555160f47,2017-01-13 19:15:53 UTC+0000,25f22b1be4d5466b961542d45070b1c0,a72bde6ac9e349d195a6d356444c9578,2,1,0
6933,ff798f02dd91487bbe1db8f5cd369536,2018-03-02 21:34:06 UTC+0000,afc4fe7668714bc8a0b936029af29595,46be2cf3b8fc49b6b8b3e62ee72a75fe,1,1,1
3259,ff692fbec8174535b8996aad239f0d8f,2016-05-02 23:45:23 UTC+0000,122a1945e5a4402b8498d8d56a66efc7,9cedda83713f492cbc45a2d1999d41a1,2,1,1
3260,ff692fbec8174535b8996aad239f0d8f,2016-05-03 18:14:46 UTC+0000,010b1d0f729147fc8c04bfe25cf1416f,a921153ba3114aaaaa60fdd5908d7a80,1,1,0
975,ff61e9c5edab4730b95b9b5a5ad22521,2014-03-12 20:36:56 UTC+0000,f30c11fc50c1416ab0bb8832b2fcfb75,2adab7916b3747af85b2d82e188c1dc3,4,4,1
1252,ff5c2567db8f4514b3a5924bb17b8613,2014-04-08 18:38:25 UTC+0000,e14ed3431f1f4a6782dfba1190016eb0,24fac8940aff427c848b2a59265c1204,1,2,1
3146,ff55f240ea6746be9f8443eb4aff9e7e,2014-04-10 03:39:36 UTC+0000,9fbc7b1de5794975b3a574b8d69abe01,6774ee9e8f9247728dbbe896726e911a,1,1,1
6445,ff4237248d494dbea25d4404a0f7ce65,2016-02-17 17:47:56 UTC+0000,c6fd06cf931e4f8a8ed1b2c5975cacf7,a1006e6a58a0447592e2435caa230f78,2,1,1
6446,ff4237248d494dbea25d4404a0f7ce65,2016-02-17 22:30:07 UTC+0000,85f96be4fbbd40debdba2aafeb043eac,36ff3b3666df400f956f8335cf53e09e,0,1,0
6447,ff4237248d494dbea25d4404a0f7ce65,2016-02-17 23:43:29 UTC+0000,fb3674ba521d44faa9351fa7f9642655,36ff3b3666df400f956f8335cf53e09e,0,2,0
5864,ff398e9a1f0042d1bd86efcd37238659,2015-03-09 20:40:26 UTC+0000,62e524ee9d0c4f08acad62896915745f,bc46e3699d92477ba8c7aa723e54a151,3,1,1
5448,ff370f5516984405be75626575377889,2012-09-08 15:32:20 UTC+0000,d7ccd7bece7e4e48bdd1c3c23b4053d0,38bc1866f29744f9a003e2e826e3fcb1,2,2,1
5449,ff370f5516984405be75626575377889,2012-09-08 18:31:29 UTC+0000,5932eb5dc2064f9485b4776e47d96fba,8442ddfd38bc422fb4677785db0630e6,0,2,0
1795,ff2fd106d1b34701a6d065dfa4cb35ab,2016-10-23 21:29:22 UTC+0000,15680f43b0ad40089d1c9378d5c181d7,5f95b0ac821e4e8e9b4fa9fc8eb9ff61,2,1,1
4716,ff2001540cc841818d434284446f2d7b,2018-01-17 05:22:00 UTC+0000,7fdbb5a38ced4ed5b885b13a7d38b88c,49ad078f92f74c5ea4892fdc9337b926,2,3,1
4717,ff2001540cc841818d434284446f2d7b,2018-02-18 17:21:35 UTC+0000,ff403503a12b424788740ebd8a5918bb,8ce1dca4e94240239e4385ed22ef43ce,1,2,0
1010,fee844aab7a147c2816bc2f1d3c20dbf,2019-01-28 23:57:24 UTC+0000,30901132449849b2aa18f308306e89a2,d02f6d9faac24997a7003a59e5f34bd3,1,2,1
6805,fece32ef57304e7eb3d88f2fa74c826d,2015-10-25 21:04:18 UTC+0000,c51887df20b941e48b8bbde8b1c87324,a1006e6a58a0447592e2435caa230f78,1,1,1
3408,fec9bd052db1463db19d54e087008671,2016-11-11 21:36:15 UTC+0000,059576c0c2f7444bb985dbc56dc2f13e,2345ff01e35a45a4bb9f863c2907be39,2,1,1
7057,fec5ff8a51914a378111db5db8828fc1,2016-06-22 05:14:03 UTC+0000,69daf88afa2147248c19a805c0fd3fc5,4dc7d9040592416f98c0bef1ad2c31f5,0,1,1
3880,febab3205ee148c380e0eeb6bfa0c45e,2016-04-29 19:27:27 UTC+0000,c8a9a66253974619beb6d551186f64a9,369f1c8646b649f6997eae7809696bd5,0,1,1
3638,feb9306289f44ede92c94656d153a766,2018-09-03 05:19:06 UTC+0000,fa4416613920459a8a91b1f2bb5d8b28,0d4cd29c55c64547b0488a9cdcb218ce,0,1,1
1632,fea935775d7c466ca5cb947cc0421062,2016-05-04 22:36:41 UTC+0000,b6307856e59a40579c5d779419eb8438,656f79a3e38d46f8b6a311209cec6690,1,1,1
2845,fea6b8dbb0c54fe583d9c75729a0d19c,2018-08-20 15:04:23 UTC+0000,0688b307d52e427b915b385ef0f2a3ad,36ff3b3666df400f956f8335cf53e09e,0,1,1
...,...,...,...,...,...,...,...
2162,fd23df0863d6494785782e2775f09ebb,2017-05-27 19:38:45 UTC+0000,57061560969344caaba3439c2afb4861,be5d23056fcb4f1287c823beec5291e1,1,2,1
2163,fd23df0863d6494785782e2775f09ebb,2017-05-30 15:40:25 UTC+0000,ff101e25c11545bb9c9dae4f6b35b858,85f378f43eee44c986addf5fc27038ce,1,1,0
7749,fd0392951d424546bb3e4670ae5dcb12,2016-12-14 13:49:43 UTC+0000,a73a790c5aaa4d69bd990f5ff956c4e7,9a16c085d12445a49a2faf2a3c68a4b8,1,3,1
2195,fcfbdf7edc3142b0b65fdcbca38d4e45,2016-03-17 18:59:56 UTC+0000,b869a5714aa2496ab15a713d95ca7757,e445f0a390ef45b8987347f6054bc8c8,1,2,1
2197,fcfbdf7edc3142b0b65fdcbca38d4e45,2016-05-06 16:07:01 UTC+0000,d1df4b3fc2b74ff1b108d239579c3603,20ab587de66a4f72bad357df52b38e32,0,2,0
2196,fcfbdf7edc3142b0b65fdcbca38d4e45,2016-05-10 00:01:28 UTC+0000,a1aed5db6b9a40f1a9be7c5117ef7e11,51e60735f7744038a079830cef89540b,0,1,0
4893,fcf3461a2f3c4415a62edee9c4e98c04,2017-01-26 18:22:03 UTC+0000,0f5f3d188d4d4dffb5002a03c8287adc,5688325ccc864f5fb814dbb388f83411,0,1,1
2669,fcf0676436dc471ebf54bea9bb1b7aa3,2015-02-26 16:53:23 UTC+0000,4534d593a0ef4c359e4c46b75f486bf5,77e2af08888a4965aad9689d9b9b34a1,2,1,1
4174,fcee43dddcf546baa6837013213de7f5,2018-05-01 13:12:44 UTC+0000,984c279b69d84c72bd65919ef973dfd7,4dc61581ec7b409bbd037e483f53ba0a,0,1,1
7909,fcec198d49b541b2846008718b17a13e,2018-01-24 18:24:08 UTC+0000,bfb0030ceb65413ab41f113693220304,12dd7a9788bf47078e0a123d3677aa0b,2,2,1
3505,fcb9e0d5959441feb0d781f06cf4eb01,2017-02-19 15:25:06 UTC+0000,ebd04c372f944480a996d74e9bda40fe,36ff3b3666df400f956f8335cf53e09e,3,2,1
3506,fcb9e0d5959441feb0d781f06cf4eb01,2017-03-12 00:53:36 UTC+0000,056122fe28424daab1f55c44d9b3d6c6,be5d23056fcb4f1287c823beec5291e1,1,1,0
736,fca9a434ed8045f58950d24e66d7a4b3,2016-06-22 19:55:20 UTC+0000,5ac52c1a206d4f309f8aee8f41dbec34,fe5fc534894e45c191e87f8c2ea0c6bd,3,6,1
6822,fca7b7455bb44bb2ae6f8360a110aafd,2017-02-09 17:24:59 UTC+0000,b28b97cbb3ab4dddac3d041c45e51bb9,d67ce930870945109a7ad86d29ba2035,1,1,1
6823,fca7b7455bb44bb2ae6f8360a110aafd,2017-02-13 07:31:04 UTC+0000,c945436133f241d3871ae87aa709362b,51a38e3c7e264f27a71ccd481ee46321,0,1,0
469,fca26e9d66af4e2e841f2394dc5b746a,2014-11-05 02:04:48 UTC+0000,483ce14b70b440eea0c5bb1d1ef8c27b,1d8d4ea9cd03402cb4b34aa41ad9f3a0,1,1,1
123,fc9b180ee0894c5ba33cbed6752773bb,2017-03-19 00:12:19 UTC+0000,463310880b5b4e8d8f29bb32819e8fcd,34ed19c6ac89412d9ed7b2f31cb394a0,1,2,1
1959,fc9628d58ecc428fa52620325c1a6eef,2015-05-19 17:20:56 UTC+0000,07061ca4b23d4fa39302cebca9d14641,b403493d43fe434c98ee997ab23de7f3,1,1,1
272,fc953e7a31b94a31801c5a5c5a7de51f,2018-06-22 05:22:36 UTC+0000,4df796a27de04f52a7023cb1f20fd25a,59ad63ce14fe4cf2bad9f3de2501a324,0,1,1
273,fc953e7a31b94a31801c5a5c5a7de51f,2018-06-23 04:33:40 UTC+0000,8384c5ca035f4523807e9b88b5c2ac07,be5d23056fcb4f1287c823beec5291e1,0,1,0
274,fc953e7a31b94a31801c5a5c5a7de51f,2018-06-24 04:25:08 UTC+0000,72165e9be4834c8c829804ed981b1574,c47b6884406e47858e87ed90153ff6b1,0,1,0
5056,fc8dc26ff8b5453095cf9299250ce07c,2016-10-23 01:12:22 UTC+0000,22af31a78605407cb3dffd9d7e56ee5b,36ff3b3666df400f956f8335cf53e09e,0,1,1
7755,fc8cad6f0efa47ac96c62fb29e288a0c,2016-03-23 08:21:24 UTC+0000,7cbcac657b6144b3b839c66e57c35624,0487120f6a2545048565c620542ead2f,4,2,1
7382,fc86f9a5287446f79717a61b0e472a4d,2014-04-30 00:01:09 UTC+0000,8c1d9b1dfe564da2997f6126632e3d79,fe4543418c0846e5a65fa22b4ad9a304,1,2,1
7904,fc7f8b830f9748239127709ee31f0dd9,2016-10-24 13:27:49 UTC+0000,1d3c7f6fee384780b62938828df1dd6e,899d9edd944048aaae4faf23bc96493a,0,1,1
870,fc7be362b0ef4207bd5751c725542cb9,2018-11-01 02:26:11 UTC+0000,88c436dda5464679b3978a561c362631,a7bf251a290b418e923e8f04a67b7ebb,2,1,1
868,fc7be362b0ef4207bd5751c725542cb9,2018-11-27 20:00:15 UTC+0000,1205f8af37c7444d820b4e6e57c40103,f9277463d7db44cfa990ee71f2797353,1,1,0
871,fc7be362b0ef4207bd5751c725542cb9,2018-11-27 21:39:01 UTC+0000,410d1075f4a44559a70d730c8f7f527d,7ed028801e0a4a08a2ce89194966efef,2,1,0
869,fc7be362b0ef4207bd5751c725542cb9,2018-12-05 17:59:20 UTC+0000,871e01a4a9ae4f0f825a76069945d7ff,1265f5c25f4b4594862de1f4104d9724,1,1,0
2043,fc75f7cbffe541419a9ba0bb7e278eba,2018-03-02 23:15:34 UTC+0000,85d8ff642dbe4cc7acfeb4aef991fbc3,4635dfed8f674c0eb5d40fca91b42599,1,1,1

In [158]:
df['n_score'] = df['score']
df.loc[df['score'] > 0, 'n_score'] = 1

df.head(10)

,answers_question_id,answers_date_added,answers_id,answers_author_id,score,comments,q_score,n_score
1818,ffe4f998cf7c4bf5a38f5406db1ca746,2018-03-01 00:41:33 UTC+0000,1190ed4125aa4a2493b40ad9e37bca9c,84e133c3aa6b402392920181f7077830,1,1,1,1
7074,ffe4bf409a1a48baa004654eb0d2e6f2,2017-02-24 02:18:24 UTC+0000,b98a4e35599e44d495022c71ac3f5516,1806af6b93c74d159c7aad68c6e7a35e,0,1,1,0
6215,ffc401dcce5d437c86f5f0576c5f3d69,2017-03-25 15:15:33 UTC+0000,45c0a57deead4bd0b641b047aa0ddcd7,65cd85193d2d43c385ca5a5abce62e63,0,1,1,0
1684,ffc201f33712429a8e9feb51f106cdf8,2015-09-18 19:06:42 UTC+0000,2657812dde9648c69438e3ca87d07625,a1006e6a58a0447592e2435caa230f78,1,3,1,1
1899,ffbbae76b05e4eacbe7d358d041bbe19,2016-10-26 01:22:51 UTC+0000,f9c0a616e8904dcbab66ca15091e45f7,fafeba89ca764bd891862fb8440a2962,0,1,1,0
7766,ff91b4d257d049d5b311dba555160f47,2017-01-13 14:08:21 UTC+0000,3f48f0a6f2c54a4eb48cb6950a997214,36ff3b3666df400f956f8335cf53e09e,1,2,1,1
7767,ff91b4d257d049d5b311dba555160f47,2017-01-13 19:15:53 UTC+0000,25f22b1be4d5466b961542d45070b1c0,a72bde6ac9e349d195a6d356444c9578,2,1,0,1
6933,ff798f02dd91487bbe1db8f5cd369536,2018-03-02 21:34:06 UTC+0000,afc4fe7668714bc8a0b936029af29595,46be2cf3b8fc49b6b8b3e62ee72a75fe,1,1,1,1
3259,ff692fbec8174535b8996aad239f0d8f,2016-05-02 23:45:23 UTC+0000,122a1945e5a4402b8498d8d56a66efc7,9cedda83713f492cbc45a2d1999d41a1,2,1,1,1
3260,ff692fbec8174535b8996aad239f0d8f,2016-05-03 18:14:46 UTC+0000,010b1d0f729147fc8c04bfe25cf1416f,a921153ba3114aaaaa60fdd5908d7a80,1,1,0,1

In [159]:
df['total_score'] = df.apply(lambda row: row['comments' : 'n_score'].sum(),axis=1)

In [160]:
df.head()

,answers_question_id,answers_date_added,answers_id,answers_author_id,score,comments,q_score,n_score,total_score
1818,ffe4f998cf7c4bf5a38f5406db1ca746,2018-03-01 00:41:33 UTC+0000,1190ed4125aa4a2493b40ad9e37bca9c,84e133c3aa6b402392920181f7077830,1,1,1,1,3
7074,ffe4bf409a1a48baa004654eb0d2e6f2,2017-02-24 02:18:24 UTC+0000,b98a4e35599e44d495022c71ac3f5516,1806af6b93c74d159c7aad68c6e7a35e,0,1,1,0,2
6215,ffc401dcce5d437c86f5f0576c5f3d69,2017-03-25 15:15:33 UTC+0000,45c0a57deead4bd0b641b047aa0ddcd7,65cd85193d2d43c385ca5a5abce62e63,0,1,1,0,2
1684,ffc201f33712429a8e9feb51f106cdf8,2015-09-18 19:06:42 UTC+0000,2657812dde9648c69438e3ca87d07625,a1006e6a58a0447592e2435caa230f78,1,3,1,1,5
1899,ffbbae76b05e4eacbe7d358d041bbe19,2016-10-26 01:22:51 UTC+0000,f9c0a616e8904dcbab66ca15091e45f7,fafeba89ca764bd891862fb8440a2962,0,1,1,0,2

In [161]:
df_f = df.sort_values(by = ['answers_question_id','total_score'], ascending = [False, True])

In [162]:
df_f.head(100)

,answers_question_id,answers_date_added,answers_id,answers_author_id,score,comments,q_score,n_score,total_score
1818,ffe4f998cf7c4bf5a38f5406db1ca746,2018-03-01 00:41:33 UTC+0000,1190ed4125aa4a2493b40ad9e37bca9c,84e133c3aa6b402392920181f7077830,1,1,1,1,3
7074,ffe4bf409a1a48baa004654eb0d2e6f2,2017-02-24 02:18:24 UTC+0000,b98a4e35599e44d495022c71ac3f5516,1806af6b93c74d159c7aad68c6e7a35e,0,1,1,0,2
6215,ffc401dcce5d437c86f5f0576c5f3d69,2017-03-25 15:15:33 UTC+0000,45c0a57deead4bd0b641b047aa0ddcd7,65cd85193d2d43c385ca5a5abce62e63,0,1,1,0,2
1684,ffc201f33712429a8e9feb51f106cdf8,2015-09-18 19:06:42 UTC+0000,2657812dde9648c69438e3ca87d07625,a1006e6a58a0447592e2435caa230f78,1,3,1,1,5
1899,ffbbae76b05e4eacbe7d358d041bbe19,2016-10-26 01:22:51 UTC+0000,f9c0a616e8904dcbab66ca15091e45f7,fafeba89ca764bd891862fb8440a2962,0,1,1,0,2
7767,ff91b4d257d049d5b311dba555160f47,2017-01-13 19:15:53 UTC+0000,25f22b1be4d5466b961542d45070b1c0,a72bde6ac9e349d195a6d356444c9578,2,1,0,1,2
7766,ff91b4d257d049d5b311dba555160f47,2017-01-13 14:08:21 UTC+0000,3f48f0a6f2c54a4eb48cb6950a997214,36ff3b3666df400f956f8335cf53e09e,1,2,1,1,4
6933,ff798f02dd91487bbe1db8f5cd369536,2018-03-02 21:34:06 UTC+0000,afc4fe7668714bc8a0b936029af29595,46be2cf3b8fc49b6b8b3e62ee72a75fe,1,1,1,1,3
3260,ff692fbec8174535b8996aad239f0d8f,2016-05-03 18:14:46 UTC+0000,010b1d0f729147fc8c04bfe25cf1416f,a921153ba3114aaaaa60fdd5908d7a80,1,1,0,1,2
3259,ff692fbec8174535b8996aad239f0d8f,2016-05-02 23:45:23 UTC+0000,122a1945e5a4402b8498d8d56a66efc7,9cedda83713f492cbc45a2d1999d41a1,2,1,1,1,3
975,ff61e9c5edab4730b95b9b5a5ad22521,2014-03-12 20:36:56 UTC+0000,f30c11fc50c1416ab0bb8832b2fcfb75,2adab7916b3747af85b2d82e188c1dc3,4,4,1,1,6
1252,ff5c2567db8f4514b3a5924bb17b8613,2014-04-08 18:38:25 UTC+0000,e14ed3431f1f4a6782dfba1190016eb0,24fac8940aff427c848b2a59265c1204,1,2,1,1,4
3146,ff55f240ea6746be9f8443eb4aff9e7e,2014-04-10 03:39:36 UTC+0000,9fbc7b1de5794975b3a574b8d69abe01,6774ee9e8f9247728dbbe896726e911a,1,1,1,1,3
6446,ff4237248d494dbea25d4404a0f7ce65,2016-02-17 22:30:07 UTC+0000,85f96be4fbbd40debdba2aafeb043eac,36ff3b3666df400f956f8335cf53e09e,0,1,0,0,1
6447,ff4237248d494dbea25d4404a0f7ce65,2016-02-17 23:43:29 UTC+0000,fb3674ba521d44faa9351fa7f9642655,36ff3b3666df400f956f8335cf53e09e,0,2,0,0,2
6445,ff4237248d494dbea25d4404a0f7ce65,2016-02-17 17:47:56 UTC+0000,c6fd06cf931e4f8a8ed1b2c5975cacf7,a1006e6a58a0447592e2435caa230f78,2,1,1,1,3
5864,ff398e9a1f0042d1bd86efcd37238659,2015-03-09 20:40:26 UTC+0000,62e524ee9d0c4f08acad62896915745f,bc46e3699d92477ba8c7aa723e54a151,3,1,1,1,3
5449,ff370f5516984405be75626575377889,2012-09-08 18:31:29 UTC+0000,5932eb5dc2064f9485b4776e47d96fba,8442ddfd38bc422fb4677785db0630e6,0,2,0,0,2
5448,ff370f5516984405be75626575377889,2012-09-08 15:32:20 UTC+0000,d7ccd7bece7e4e48bdd1c3c23b4053d0,38bc1866f29744f9a003e2e826e3fcb1,2,2,1,1,4
1795,ff2fd106d1b34701a6d065dfa4cb35ab,2016-10-23 21:29:22 UTC+0000,15680f43b0ad40089d1c9378d5c181d7,5f95b0ac821e4e8e9b4fa9fc8eb9ff61,2,1,1,1,3
4717,ff2001540cc841818d434284446f2d7b,2018-02-18 17:21:35 UTC+0000,ff403503a12b424788740ebd8a5918bb,8ce1dca4e94240239e4385ed22ef43ce,1,2,0,1,3
4716,ff2001540cc841818d434284446f2d7b,2018-01-17 05:22:00 UTC+0000,7fdbb5a38ced4ed5b885b13a7d38b88c,49ad078f92f74c5ea4892fdc9337b926,2,3,1,1,5
1010,fee844aab7a147c2816bc2f1d3c20dbf,2019-01-28 23:57:24 UTC+0000,30901132449849b2aa18f308306e89a2,d02f6d9faac24997a7003a59e5f34bd3,1,2,1,1,4
6805,fece32ef57304e7eb3d88f2fa74c826d,2015-10-25 21:04:18 UTC+0000,c51887df20b941e48b8bbde8b1c87324,a1006e6a58a0447592e2435caa230f78,1,1,1,1,3
3408,fec9bd052db1463db19d54e087008671,2016-11-11 21:36:15 UTC+0000,059576c0c2f7444bb985dbc56dc2f13e,2345ff01e35a45a4bb9f863c2907be39,2,1,1,1,3
7057,fec5ff8a51914a378111db5db8828fc1,2016-06-22 05:14:03 UTC+0000,69daf88afa2147248c19a805c0fd3fc5,4dc7d9040592416f98c0bef1ad2c31f5,0,1,1,0,2
3880,febab3205ee148c380e0eeb6bfa0c45e,2016-04-29 19:27:27 UTC+0000,c8a9a66253974619beb6d551186f64a9,369f1c8646b649f6997eae7809696bd5,0,1,1,0,2
3638,feb9306289f44ede92c94656d153a766,2018-09-03 05:19:06 UTC+0000,fa4416613920459a8a91b1f2bb5d8b28,0d4cd29c55c64547b0488a9cdcb218ce,0,1,1,0,2
1632,fea935775d7c466ca5cb947cc0421062,2016-05-04 22:36:41 UTC+0000,b6307856e59a40579c5d779419eb8438,656f79a3e38d46f8b6a311209cec6690,1,1,1,1,3
2845,fea6b8dbb0c54fe583d9c75729a0d19c,2018-08-20 15:04:23 UTC+0000,0688b307d52e427b915b385ef0f2a3ad,36ff3b3666df400f956f8335cf53e09e,0,1,1,0,2
...,...,...,...,...,...,...,...,...,...
2163,fd23df0863d6494785782e2775f09ebb,2017-05-30 15:40:25 UTC+0000,ff101e25c11545bb9c9dae4f6b35b858,85f378f43eee44c986addf5fc27038ce,1,1,0,1,2
2162,fd23df0863d6494785782e2775f09ebb,2017-05-27 19:38:45 UTC+0000,57061560969344caaba3439c2afb4861,be5d23056fcb4f1287c823beec5291e1,1,2,1,1,4
7749,fd0392951d424546bb3e4670ae5dcb12,2016-12-14 13:49:43 UTC+0000,a73a790c5aaa4d69bd990f5ff956c4e7,9a16c085d12445a49a2faf2a3c68a4b8,1,3,1,1,5
2196,fcfbdf7edc3142b0b65fdcbca38d4e45,2016-05-10 00:01:28 UTC+0000,a1aed5db6b9a40f1a9be7c5117ef7e11,51e60735f7744038a079830cef89540b,0,1,0,0,1
2197,fcfbdf7edc3142b0b65fdcbca38d4e45,2016-05-06 16:07:01 UTC+0000,d1df4b3fc2b74ff1b108d239579c3603,20ab587de66a4f72bad357df52b38e32,0,2,0,0,2
2195,fcfbdf7edc3142b0b65fdcbca38d4e45,2016-03-17 18:59:56 UTC+0000,b869a5714aa2496ab15a713d95ca7757,e445f0a390ef45b8987347f6054bc8c8,1,2,1,1,4
4893,fcf3461a2f3c4415a62edee9c4e98c04,2017-01-26 18:22:03 UTC+0000,0f5f3d188d4d4dffb5002a03c8287adc,5688325ccc864f5fb814dbb388f83411,0,1,1,0,2
2669,fcf0676436dc471ebf54bea9bb1b7aa3,2015-02-26 16:53:23 UTC+0000,4534d593a0ef4c359e4c46b75f486bf5,77e2af08888a4965aad9689d9b9b34a1,2,1,1,1,3
4174,fcee43dddcf546baa6837013213de7f5,2018-05-01 13:12:44 UTC+0000,984c279b69d84c72bd65919ef973dfd7,4dc61581ec7b409bbd037e483f53ba0a,0,1,1,0,2
7909,fcec198d49b541b2846008718b17a13e,2018-01-24 18:24:08 UTC+0000,bfb0030ceb65413ab41f113693220304,12dd7a9788bf47078e0a123d3677aa0b,2,2,1,1,4
3506,fcb9e0d5959441feb0d781f06cf4eb01,2017-03-12 00:53:36 UTC+0000,056122fe28424daab1f55c44d9b3d6c6,be5d23056fcb4f1287c823beec5291e1,1,1,0,1,2
3505,fcb9e0d5959441feb0d781f06cf4eb01,2017-02-19 15:25:06 UTC+0000,ebd04c372f944480a996d74e9bda40fe,36ff3b3666df400f956f8335cf53e09e,3,2,1,1,4
736,fca9a434ed8045f58950d24e66d7a4b3,2016-06-22 19:55:20 UTC+0000,5ac52c1a206d4f309f8aee8f41dbec34,fe5fc534894e45c191e87f8c2ea0c6bd,3,6,1,1,8
6823,fca7b7455bb44bb2ae6f8360a110aafd,2017-02-13 07:31:04 UTC+0000,c945436133f241d3871ae87aa709362b,51a38e3c7e264f27a71ccd481ee46321,0,1,0,0,1
6822,fca7b7455bb44bb2ae6f8360a110aafd,2017-02-09 17:24:59 UTC+0000,b28b97cbb3ab4dddac3d041c45e51bb9,d67ce930870945109a7ad86d29ba2035,1,1,1,1,3
469,fca26e9d66af4e2e841f2394dc5b746a,2014-11-05 02:04:48 UTC+0000,483ce14b70b440eea0c5bb1d1ef8c27b,1d8d4ea9cd03402cb4b34aa41ad9f3a0,1,1,1,1,3
123,fc9b180ee0894c5ba33cbed6752773bb,2017-03-19 00:12:19 UTC+0000,463310880b5b4e8d8f29bb32819e8fcd,34ed19c6ac89412d9ed7b2f31cb394a0,1,2,1,1,4
1959,fc9628d58ecc428fa52620325c1a6eef,2015-05-19 17:20:56 UTC+0000,07061ca4b23d4fa39302cebca9d14641,b403493d43fe434c98ee997ab23de7f3,1,1,1,1,3
273,fc953e7a31b94a31801c5a5c5a7de51f,2018-06-23 04:33:40 UTC+0000,8384c5ca035f4523807e9b88b5c2ac07,be5d23056fcb4f1287c823beec5291e1,0,1,0,0,1
274,fc953e7a31b94a31801c5a5c5a7de51f,2018-06-24 04:25:08 UTC+0000,72165e9be4834c8c829804ed981b1574,c47b6884406e47858e87ed90153ff6b1,0,1,0,0,1
272,fc953e7a31b94a31801c5a5c5a7de51f,2018-06-22 05:22:36 UTC+0000,4df796a27de04f52a7023cb1f20fd25a,59ad63ce14fe4cf2bad9f3de2501a324,0,1,1,0,2
5056,fc8dc26ff8b5453095cf9299250ce07c,2016-10-23 01:12:22 UTC+0000,22af31a78605407cb3dffd9d7e56ee5b,36ff3b3666df400f956f8335cf53e09e,0,1,1,0,2
7755,fc8cad6f0efa47ac96c62fb29e288a0c,2016-03-23 08:21:24 UTC+0000,7cbcac657b6144b3b839c66e57c35624,0487120f6a2545048565c620542ead2f,4,2,1,1,4
7382,fc86f9a5287446f79717a61b0e472a4d,2014-04-30 00:01:09 UTC+0000,8c1d9b1dfe564da2997f6126632e3d79,fe4543418c0846e5a65fa22b4ad9a304,1,2,1,1,4
7904,fc7f8b830f9748239127709ee31f0dd9,2016-10-24 13:27:49 UTC+0000,1d3c7f6fee384780b62938828df1dd6e,899d9edd944048aaae4faf23bc96493a,0,1,1,0,2
868,fc7be362b0ef4207bd5751c725542cb9,2018-11-27 20:00:15 UTC+0000,1205f8af37c7444d820b4e6e57c40103,f9277463d7db44cfa990ee71f2797353,1,1,0,1,2
871,fc7be362b0ef4207bd5751c725542cb9,2018-11-27 21:39:01 UTC+0000,410d1075f4a44559a70d730c8f7f527d,7ed028801e0a4a08a2ce89194966efef,2,1,0,1,2
869,fc7be362b0ef4207bd5751c725542cb9,2018-12-05 17:59:20 UTC+0000,871e01a4a9ae4f0f825a76069945d7ff,1265f5c25f4b4594862de1f4104d9724,1,1,0,1,2
870,fc7be362b0ef4207bd5751c725542cb9,2018-11-01 02:26:11 UTC+0000,88c436dda5464679b3978a561c362631,a7bf251a290b418e923e8f04a67b7ebb,2,1,1,1,3
2043,fc75f7cbffe541419a9ba0bb7e278eba,2018-03-02 23:15:34 UTC+0000,85d8ff642dbe4cc7acfeb4aef991fbc3,4635dfed8f674c0eb5d40fca91b42599,1,1,1,1,3

In [163]:
final_db = df.loc[df.groupby('answers_question_id')['total_score'].idxmax().values.ravel()]

In [164]:
final_db.head()

,answers_question_id,answers_date_added,answers_id,answers_author_id,score,comments,q_score,n_score,total_score
7773,000b30fb534b41f7b716fa9ebf9c3f35,2016-05-19 18:54:34 UTC+0000,987a377658c0439a8f1e74117531eb2a,9d3d0927a8684e179eaf640c9dfd66ac,0,5,1,0,6
2766,002b07f6281a407ca49ee8b3538e5e45,2014-11-07 23:33:24 UTC+0000,698be6047aa246788a610aebc9f1f2db,c12dff6c1c844bac95ce8a96e8a47c61,3,12,1,1,14
3269,00361e5dda874e65abaeeceb12c8e10c,2018-11-14 17:40:01 UTC+0000,f6c60d3eda104ece8a8aa74745f4fe54,38780fb1cb0b4d5594af5c402ef4e3b3,0,1,1,0,2
7747,0037ccbe4467439490e660f606addf2b,2018-02-07 03:52:59 UTC+0000,478125b32a4f41d49a3d9eb37c3beef0,ef8a09c1c2af45aab9f7cefc16f98cd5,3,1,1,1,3
1190,006b9cf69cd0405ea0a8821c5f6641bb,2016-12-01 18:57:49 UTC+0000,0eb97b322dc84bea922833ca09168ccc,96bbbdd06a334805a0501034d9df1aa4,2,1,1,1,3

In [165]:
p_df = pd.read_csv("professionals.csv")

In [166]:
p_df.head()

,professionals_id,professionals_location,professionals_industry,professionals_headline,professionals_date_joined
0,9ced4ce7519049c0944147afb75a8ce3,NaN,NaN,NaN,2011-10-05 20:35:19 UTC+0000
1,f718dcf6d2ec4cb0a52a9db59d7f9e67,NaN,NaN,NaN,2011-10-05 20:49:21 UTC+0000
2,0c673e046d824ec0ad0ebe012a0673e4,"New York, New York",NaN,NaN,2011-10-18 17:31:26 UTC+0000
3,977428d851b24183b223be0eb8619a8c,"Boston, Massachusetts",NaN,NaN,2011-11-09 20:39:29 UTC+0000
4,e2d57e5041a44f489288397c9904c2b2,NaN,NaN,NaN,2011-12-10 22:14:44 UTC+0000

In [167]:
p_df.rename(columns={'professionals_id':'answers_author_id'}, 
                 inplace=True)

In [168]:
p_df["professionals_industry"].fillna("Other", inplace = True)

In [169]:
p_df.head()

,answers_author_id,professionals_location,professionals_industry,professionals_headline,professionals_date_joined
0,9ced4ce7519049c0944147afb75a8ce3,NaN,Other,NaN,2011-10-05 20:35:19 UTC+0000
1,f718dcf6d2ec4cb0a52a9db59d7f9e67,NaN,Other,NaN,2011-10-05 20:49:21 UTC+0000
2,0c673e046d824ec0ad0ebe012a0673e4,"New York, New York",Other,NaN,2011-10-18 17:31:26 UTC+0000
3,977428d851b24183b223be0eb8619a8c,"Boston, Massachusetts",Other,NaN,2011-11-09 20:39:29 UTC+0000
4,e2d57e5041a44f489288397c9904c2b2,NaN,Other,NaN,2011-12-10 22:14:44 UTC+0000

In [170]:
df = pd.merge(p_df, final_db, on='answers_author_id')
df.head()

,answers_author_id,professionals_location,professionals_industry,professionals_headline,professionals_date_joined,answers_question_id,answers_date_added,answers_id,score,comments,q_score,n_score,total_score
0,0c673e046d824ec0ad0ebe012a0673e4,"New York, New York",Other,NaN,2011-10-18 17:31:26 UTC+0000,0914db8647f14ed18ab2a7b321d0b81d,2012-10-15 01:02:00 UTC+0000,72798b8492314e12980a1503633d6569,0,1,1,0,2
1,0c673e046d824ec0ad0ebe012a0673e4,"New York, New York",Other,NaN,2011-10-18 17:31:26 UTC+0000,2c5bd5eb628245acb868c81fefcfe5e0,2012-02-13 00:49:26 UTC+0000,281c2557f0154dde984707e40100b8b4,19,3,1,1,5
2,0c673e046d824ec0ad0ebe012a0673e4,"New York, New York",Other,NaN,2011-10-18 17:31:26 UTC+0000,2f2378acab3f444199ee2b69d2d3626f,2012-09-09 13:36:44 UTC+0000,63b7a06323ee4d578a37cf780debfa58,3,1,1,1,3
3,0c673e046d824ec0ad0ebe012a0673e4,"New York, New York",Other,NaN,2011-10-18 17:31:26 UTC+0000,333464d7484b43e3866e86096bc4ddb9,2011-10-18 19:14:15 UTC+0000,683b200ad5014e84a441db677f990d75,3,1,1,1,3
4,0c673e046d824ec0ad0ebe012a0673e4,"New York, New York",Other,NaN,2011-10-18 17:31:26 UTC+0000,5bd585028efe49f4b89701b84e6fbe8c,2012-06-03 21:05:38 UTC+0000,d0388adf192c4683a1d9a079f88fbd52,1,1,1,1,3

In [171]:
clean_df = df.filter(['answers_question_id','answers_id','professionals_industry'])

prof = clean_df.sort_values(by = ['professionals_industry'], ascending = True)

In [172]:
p = prof.groupby('professionals_industry').count()
p['new_col'] = range(1, len(p) + 1)

p.head(50)

,answers_question_id,answers_id,new_col
professionals_industry,,,
ARCHITECTURE_AND_PLANNING,3,3,1
Academia,1,1,2
Academic Advisor,2,2,3
Accounting,72,72,4
Accounting & Finance,1,1,5
"Accounting (broker dealers, hedge funds, private equity)",1,1,6
"Accounting, Tax, Operations, Technology",1,1,7
"Accounting, education",2,2,8
Accounting/ Information Technology,1,1,9
Accounting/Auditing/Learning & Development,1,1,10
Administrative,1,1,11
Advertising Technology,2,2,12
Airbnb,1,1,13
Airlines/Aviation,22,22,14
Animal Behavior and Welfare,2,2,15
Animation,5,5,16
Apparel & Fashion,1,1,17
Apparel and Fashion,3,3,18
Architecture & Planning,8,8,19
Architecture and Planning,4,4,20
Art Education,1,1,21
Arts and Crafts,12,12,22
Automotive,201,201,23
Aviation,2,2,24
Aviation & Aerospace,9,9,25
Aviation and Aerospace,15,15,26
Banking,6,6,27
Banking/Financial,6,6,28
Biology Research,1,1,29
Biomedical research,2,2,30
Biotechnology,19,19,31
Biotechnology and Pharmaceutical,7,7,32
Broadcast Media,31,31,33
Business,1,1,34
Business Journalism,1,1,35
CIVIL_ENGINEERING,1,1,36
COMPUTER_SOFTWARE,3,3,37
CRIMINAL JUSTICE/LAW ENFORCEMENT/POLYGRAPH EXAMINER/MILITARY/BUSINESS OWNER,1,1,38
CSR,1,1,39
Capital Markets,1,1,40
Career Advising & Counseling,4,4,41
Career Coaching,1,1,42
Career Counseling,32,32,43
Career Counseling & Employment Coaching,1,1,44
Career Counseling Certification,9,9,45
Chemical Engineering,1,1,46
Chemicals,22,22,47
"Chemicals, Pharmaceuticals",2,2,48
Civic & Social Organization,19,19,49
Civic and Social Organization,1,1,50

In [173]:
pp = p.drop(['answers_question_id','answers_id'], axis = 1)

In [174]:
pp

                                                    new_col
professionals_industry
ARCHITECTURE_AND_PLANNING                                 1
Academia                                                  2
Academic Advisor                                          3
Accounting                                                4
Accounting & Finance                                      5
Accounting (broker dealers, hedge funds, privat...        6
Accounting, Tax, Operations, Technology                   7
Accounting, education                                     8
Accounting/ Information Technology                        9
Accounting/Auditing/Learning & Development               10
Administrative                                           11
Advertising Technology                                   12
Airbnb                                                   13
Airlines/Aviation                                        14
Animal Behavior and Welfare                              15
Animation                                                16
Apparel & Fashion                                        17
Apparel and Fashion                                      18
Architecture & Planning                                  19
Architecture and Planning                                20
Art Education                                            21
Arts and Crafts                                          22
Automotive                                               23
Aviation                                                 24
Aviation & Aerospace                                     25
Aviation and Aerospace                                   26
Banking                                                  27
Banking/Financial                                        28
Biology Research                                         29
Biomedical research                                      30
...                                                     ...
Technology, Accounting, Audit                           351
Telecommunications                                      352
Telecommunications / Technology                         353
Telecommunications, Software Engineering, Progr...      354
Telecommunications/Entertainment                        355
Translation and Localization                            356
Transportation/Trucking/Railroad                        357
Travel Insurance                                        358
UX Design                                               359
User Experience Design                                  360
Utilities                                               361
Venture Capital                                         362
Veterinary                                              363
Video Games                                             364
Video production/ Corporate narrative/ Business...      365
Web Design/Marketing/Advertising                        366
Web Development                                         367
Wholesale                                               368
Writing and Editing                                     369
Writing and Editing, film and photography               370
Writing and Editing/Education                           371
Writing and Editing; Education                          372
education, tech, media                                  373
entrepreneur                                            374
game                                                    375
high tech security protection                           376
iOS Development                                         377
marijuana                                               378
nonprofit / higher education                            379
video games                                             380

[380 rows x 1 columns]

In [175]:
pp.to_csv('professionals_index.csv', header= False)

In [176]:
pros_dict = pp.to_dict().get("new_col")
print(pros_dict.get("Other"))

274

In [179]:
industry_codes = []

for index, row in clean_df.iterrows():
    industry_codes.append(pros_dict[row['professionals_industry']])
    
clean_df["industry_codes"] = industry_codes
clean_df = clean_df.rename(index=str, columns={"answers_question_id": "questions_id"})
clean_df

,questions_id,answers_id,professionals_industry,industry_codes
0,0914db8647f14ed18ab2a7b321d0b81d,72798b8492314e12980a1503633d6569,Other,274
1,2c5bd5eb628245acb868c81fefcfe5e0,281c2557f0154dde984707e40100b8b4,Other,274
2,2f2378acab3f444199ee2b69d2d3626f,63b7a06323ee4d578a37cf780debfa58,Other,274
3,333464d7484b43e3866e86096bc4ddb9,683b200ad5014e84a441db677f990d75,Other,274
4,5bd585028efe49f4b89701b84e6fbe8c,d0388adf192c4683a1d9a079f88fbd52,Other,274
5,82acf6d8608b4743848d0c8c4e5c610b,ae8d6e375f804c698c324def1a3bf4f9,Other,274
6,b3534776e3854e8bb73d8a1b1be3511f,f46ad30f5220449f9ac36f66f49ba310,Other,274
7,d98717b213984ed1a715bd88367d6258,a836064f4eaf491eaeb4142e8d4cd752,Other,274
8,7f00ff6f131243c880ced983e171a085,9a2997e6ddd94c8b9a2bc00044c434d0,Other,274
9,e999912603ee4a5c908c4aa68f8f46ba,ea0d1620028e49edbce31e248e0a78e3,Other,274
10,06ab800396e0457a973affbfa935777b,490f211ff2874a24a0ec8664e590accf,Other,274
11,54daae9f120c4c1db36044da58827c83,574bd06c5e344a938795c3bbf92d0014,Other,274
12,0284380052104b3aba7e485541a36915,66172aaca725498c8042546576b7f31c,Other,274
13,0ca75abcca7d4abe91c55e282ae2a888,c5ca2fe19b8945acb9c060588ae845fd,Other,274
14,1141d4e37d1340bcb26dbb4ba84a2311,16827dbae85a4a9db4de5af5633173b7,Other,274
15,239774c8ab1c4d49a661c25a9ed7d4a1,2129421917ff4bec8e1d4d35bf059a0d,Other,274
16,2e5833f6e19e417ca6124e88a07b103d,07d6b508c024480689da399897f01128,Other,274
17,3359b5a733464520934c95d81f33047d,83da9e574bcd4b7e9b04694062072931,Other,274
18,3bc6f8ee03e9408db41defb92f03e91e,eb00049a353341ddb604e9db07e3cc1d,Other,274
19,57b71988f87446b3be35ae40ef98cb9d,32c7202096954fe59aaa3de090eff073,Other,274
20,5814bf0c788148f1b124a99fbef43080,de648e8b351d4db888f4f71bc4c2c380,Other,274
21,585833caefe84e15a0276710632a96e2,e78bc11b17d847fcb1fb391fbd8ae88a,Other,274
22,5da4e4e611854c9ca99e9c3d4413d80b,aa9952d1854d4e5696ebf94f413cd7d5,Other,274
23,6f2fa869d1904c949126818b33756ffa,c5b4c1b30a124b25a492056148ee4a2c,Other,274
24,a14e9100a0444e159f59e71b016a60ee,c8ac501ed357453d859562a0f61dd693,Other,274
25,ac089a1f25184fa491a81fa7c31a9a58,852e2a3f132b4d5482b0646dcf439f0c,Other,274
26,bc83d24465d745cb968b2e2be5626861,dee6d866fc4f4fb8a0eead4bcd8212a0,Other,274
27,c8e4178889384616b66ba95072367c22,a071915a90ff42f7a06cd861a4ac81be,Other,274
28,d558a1d8e51242d9823f29ce72030c3b,852f2850df05422883fe6189ad4ed2d2,Other,274
29,dcbb6ad4eb0840329f1747fb3a10b1fe,fead5429ccd14d14a66b8f54dea53228,Other,274
...,...,...,...,...
5142,3c2f944610264f57bd9674472728c039,6ed268c752de46e4ae08a31e7ff8ff8c,Education,100
5143,1a76a23c408341fca977d5c57ca96557,011b2f87c3314a60b4d9948132ae2f89,Other,274
5144,51298da120a6416897e334bb082f933d,d50f1e53d4b64d1ab076e892bcaf7419,Other,274
5145,9105ec834ce04a7189a94dd361dfe121,019bb09b1b0d47db8957315d54e95b85,Consumer Services,78
5146,a3b8dbd41e54411c9b454e484ed05e65,c5db48a4abcf4ba8883320bbac2fc728,Communications,56
5147,baed98b1e5dd4e5e8a247f10551ab32c,286071c21932465a8e872c4f605b16d9,Higher Education,158
5148,ebd869857f074c498430287d8d3ba004,97b9b72fcfe546ae8b0938d69dfbe3fd,Telecommunications,352
5149,7a2407eaca7343bd809833894611cbe3,e1fd89b63c964760ad2c2f924d1c9f8d,Real Estate,304
5150,33d510d344304591a4a286a38ae8980d,b5e9faa6af8643868cea8ba72bb66f42,"Technical, Finance, Real Estate, Media, Public...",346
5151,bf64dfa3a0fd47d7a9a5c2a9814c2a54,2e635650e19c4b65999c61eb0c7e73ff,"Technical, Finance, Real Estate, Media, Public...",346
5152,d717534a8cb741ff9e00fadc18025399,e5bc79dac4934d7e8d91bb295de77653,"Technical, Finance, Real Estate, Media, Public...",346
5153,ec28c434d60d4c3cadede6b1b171acd2,44fd798f15844b1abfb850486f68fe49,"Technical, Finance, Real Estate, Media, Public...",346
5154,4e24713ce3854f0db887f851d849ccd9,1bbe7e5592104838824daa4a9a241ed2,Electrical and Electronic Manufacturing,108
5155,22d8bb64b0b342cda98c1cd2da2e8cc5,c14d8592f06645baa2e73df0e1283b73,Telecommunications,352
5156,5646c7062d20460681acb806edcf5cef,4e6fb1aeafe8422884a59d5c0877518d,Telecommunications,352
5157,dcef6f036d954eaf8c2c4b2d10d7a4e2,c41ab4b10725458494525205a850df65,Financial Services,128
5158,41a8355044da4fa69d46178367ad9374,8090e331cabe4ac8b56c10708318edcd,Architecture and Planning,20
5159,905f7efff64f4148b4188a43ae59ffc1,607f69c76a0b47f3ad18b1fe98b78ec1,Education,100
5160,556a3322b0df4e25badf8c2cc36407c9,83816ac4e2f849dea631e47368289200,Community,58
5161,7717911d1d4946aabcc34b9d1ff3cf62,8e47b4a7154b4dcaa83e4ae811471852,Higher Education and Events Services,160
5162,2a90e3162b854760ab9d57abfe01afc1,75c6c116f1e6429291d70d79aed794f5,Information Technology and Services,181
5163,e74bdb86dcfa42f183b5497c16c90b72,dee2a0bb57f446578fc9c73b745c7b15,Mechanical or Industrial Engineering,227
5164,ed53ae40fca145d58ca2776dbb44e80f,abab16b7b49a4798be5594d30fe1d3aa,Telecommunications,352
5165,f2ff1183ce004206943b54dcff1faab4,4d9d7f5214634b6a8167c9fe331f7b7b,Civic and Social Organization,50
5166,1b4b1ab826184b12a13e711ec38440d4,ef4b6ae24d1f4c3b977731e8189c7fd7,Public Accounting,296
5167,96ff80ac134f4617bf5ccbe3fbf956f1,7a144ffc39844b6bbf86fd6eadc9b0ad,Telecommunications,352
5168,b169678e516d4a53b07d5b24ae91e619,13327ad8c45a4da390101e8057f801cd,Telecommunications,352
5169,7b686de628c345d0b85d59f231c31e3b,7ebb0e5e9b544c1eb0c96ffad1d73dfd,Career Coaching,42
5170,1221d83b6b394e80b13b4d14b51e28ee,5bf762c8501d450a97af992800980242,Telecommunications,352
5171,a25c4cee64974799ba0c150e6afce95f,b476f9c6d9cd4c50a7bacdd90edd015a,Information Technology and Services,181

In [180]:
clean_df.to_csv('data_with_industry_codes.csv', header= True)